### PR TITLE
linux + gcc-7 compilation fixes

### PR DESCRIPTION
**Pull request by jglauche**
gcc-7 does not accept assigning
bool* var = false;

### CODE REVIEW

**Comment by sagacrypto** [comment]
Can you please also written down your OS version, so that the solution can help new comers, because nobody complaint about this so far on Ubuntu 14.04 or 16.04. If you used same OS version that I mentioned, maybe please state any other details that you think will help. Thanks!

**Comment by jglauche** [comment]
I am using Debian sid with gcc-7.2.0
It compiled OK with gcc-5 (after the chmod +x fix. I guess you pushed into this repository from a windows machine)

**Comment by jglauche** [comment]
There was one with the same code and same problem: https://github.com/RenosCoin/RenosCoin/issues/2
which has been fixed the same way:
https://github.com/RenosCoin/RenosCoin/commit/51e260d6de2be6fd9fe60e45973ee74f16ba381e#diff-568a69d65983b416159f2a6f562c84f4

**Comment by sagacrypto** [comment]
Thank you very much. And you made the correct guess. We developed in linux but pushed in windows. Didn't know windows will create such issue. We will see how we should do in coming releases. Maybe try to use github in linux. Thanks again 👍

**Comment by jglauche** [comment]
by the way, you didn't merge the changes. 
I noticed another issue which I forgot,
you should create an empty directory  
src/obj/crypto
(with a placeholder file in it for git) 
The unix makefile assumes it's there, does not create it and fails

**Pull request closed without merging**
